[project]
name = "telia-ripper"
version = "0.2.0"
description = "Tool for downloading and decrypting (Estonian) Telia/Go3 video streams"
requires-python = ">=3.14"
dependencies = [
    "httpx",
    "python-dotenv",
]
[dependency-groups]
dev = [
    "ruff",
]
[tool.ruff.lint]
select = ["ALL"]