[project]
name = "telia-ripper"
version = "0.1.3"
description = "Tool for downloading and decrypting Telia video streams"
requires-python = ">=3.14"
dependencies = [
    "httpx",
    "python-dotenv",
]
[dependency-groups]
dev = [
    "ruff",
]
