[project]
name = "telia-ripper"
version = "0.1.1"
description = "Tool for downloading and decrypting Telia video streams"
requires-python = ">=3.13"
dependencies = [
    "httpx",
    "python-dotenv",
]
[dependency-groups]
dev = [
    "ruff",
]
